# Generated by Django 5.0.4 on 2024-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0003_danceforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceforms',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
