# Generated by Django 5.0.4 on 2024-06-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0004_alter_danceforms_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cover_img', models.ImageField(null=True, upload_to='cover image')),
                ('vdo', models.FileField(upload_to='Tutorial_vdos')),
                ('dance_forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homeapp.danceforms')),
            ],
        ),
    ]
