# Generated by Django 5.0.4 on 2024-06-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0005_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='Heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
