# Generated by Django 5.0.4 on 2024-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0006_tutorials_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='Heading',
        ),
        migrations.AddField(
            model_name='danceforms',
            name='outcomes',
            field=models.TextField(null=True),
        ),
    ]
