# Generated by Django 5.0.4 on 2024-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0010_card_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_details',
            name='Exp_year',
            field=models.CharField(choices=[('Choose Year', 'Choose Year'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], default='', max_length=20),
        ),
    ]
