# Generated by Django 5.0.4 on 2024-07-12 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeapp', '0015_tutorialprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentamount',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homeapp.danceforms'),
        ),
    ]
